dataset:
  fixed_image_shape:
  - 256
  - 128
  - 21
  moving_image_shape:
  - 256
  - 128
  - 21
  moving_label_shape:
  - 400
  - 3
  fixed_label_shape:
  - 400
  - 3
  test:
    dir:
    - "/scratch/mie8014/BAN/computer_vision/data/EY/test/sub-20190924-03"
    format: "h5"
    labeled: false
  train:
    dir:
      - "/scratch/mie8014/BAN/computer_vision/data/EY/train/sub-20190924-01"
      - "/scratch/mie8014/BAN/computer_vision/data/EY/train/sub-20190924-02"
    format: "h5"
    labeled: true
  type: paired
  valid:
    dir:
      - "/scratch/mie8014/BAN/computer_vision/data/EY/valid/sub-20190924-03"
    format: "h5"
    labeled: true
    sample_label: "all"
train:
  backbone:
    extract_levels: 
    - 0
    - 1
    - 2
    - 3
    name: "local"
    num_channel_initial: 16
  epochs: 10
  loss:
    image:
      kernel_size: 16
      name: "lncc"
      weight: 1
    label:
      name: "centroid"
      weight: 0.1
    regularization:
      hybrid: true
      img_size:
      - 256
      - 128
      - 21
      name: "hybrid"
      weight: 1
      hybrid_weight:
        "axisdiff": 0.001
        "gradient": 0.02
        "nonrigid": 0.02
        "diff": 0.005
  method: "ddf"
  optimizer:
    learning_rate: 0.0001
    name: "Adam"
  preprocess:
    batch_size: 4
    data_augmentation:
      name: "centroid_affine"
      moving_label_size:
        - 400
        - 3
      fixed_label_size:
        - 400
        - 3
    num_parallel_calls: -1
    shuffle_buffer_num_batch: 4
  save_period: 1
  single_channel: True
